NoRecipes: No recipes yet.
RecipeTitle title@Text: recipe view: #{title}
RecipeAuthorBy: by
RecipePostedOn: on
RecipeCommentsWord: comments
HomeIntro: Social cooking with friends.
Tags: Tags:
HomePageTitle: for peas (and cooking)
PreviousPage: Previous
NextPage: Next
NewRecipePageTitle: new recipe

RecipeDescriptionFormField: Description:
RecipeStepsFormField: Steps:
RecipeIngredientsFormField: Ingredients:
AddStepButton: Add Step

NotLoggedInComment: You must be logged in to post comments.

LoginLink: Login
LogoutLink: Logout