NoRecipes: No recipes yet.
RecipeTitle title@Text: recipe view: #{title}
RecipeAuthorBy: by
RecipePostedOn: on
RecipeCommentsWord: comments
HomeIntro: 4peas is a website dedicated to cooking with your friends. Submit recipes and comment on them, it's that simple.
Tags: Tags:
HomePageTitle: for peas (and cooking)
PreviousPage: Previous
NextPage: Next
NewRecipePageTitle: new recipe
EditRecipePageTitle: edit recipe
DeleteRecipePageTitle: delete recipe
LoginPageTitle: login
LoginRequired: You must be logged in to continue. Please log in with one of the following services:

RecipeNameFormField: Name:
RecipeDescriptionFormField: Description:
RecipeStepsFormField: Steps:
RecipeIngredientsFormField: Ingredients:
RecipeTagsFormField: Tags:
CommentFormField: Comment:
AddStepButton: Add Step
AddIngredientButton: Add Ingredient
AddTagButton: Add Tag

NotLoggedInComment: You must be logged in to post comments.

LoginLink: Login
LogoutLink: Logout

NoneYet: None yet.

ConfirmDeletePrompt: Are you sure you want to delete this recipe?