Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://dev.4pe.as:3000"
  copyright: Copyright (C) 2012 Mooneer Salem. 
  #facebookAppName: "4pe.as"
  #facebookAppId: 123456789
  #facebookSecret: "abc123"
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
