Default: &defaults
  database: 4peas.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: 4peas_test.sqlite3
  <<: *defaults

Staging:
  database: 4peas_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: 4peas_production.sqlite3
  poolsize: 100
  <<: *defaults
